### PR TITLE
UI cleanup

### PR DESCRIPTION
**Pull request by eldang**
This is a follow-on from https://github.com/coregis/ryht-programs-map-2021/pull/16 which unfortunately I can't continue adding to after a merge.  It addresses two issues:

1. I think I've sorted out the issue of the landing page flashing up when it's not wanted.  It's now drawn as hidden, and the logic to unhide it as appropriate runs _before_ the map is drawn, so it's quick.
2. In testing that, I was finding it confusing that the order of the radio buttons changed depending on which set of boundaries was active.  I think this made sense for 2 options but doesn't for 3, so I moved things around to keep them consistent.

I found that my browser really want to cache old files for both of these changes, so it's probably worth testing this in a private browser window.  And if these changes make sense, it's worth merging them into your WIP branch without waiting for the next things, again in the spirit of keeping any merge conflict resolution we may have to do small and incremental.

### CODE REVIEW

**Comment by eldang** [comment]
Oops, actually hold on: I found a little UI bug that's worth fixing while I'm at this.

**Comment by eldang** [comment]
OK, that turned out to be an easy fix.  Issue 3 that this PR fixes was that the word "school" was inappropriately staying visible in the `Use the drop-down menus below to zoom to a School District of your choice.` prompt text, leaving the House/Senate district versions to say "HouseSchool District" and "SenateSchool District"....  Safe to test & merge now.

**Comment by coregis** [comment]
@eldang cool, I am testing now and will merge shortly, assuming no major issues surface during the test drive

**Comment by coregis** [comment]
@eldang this is looking good, there are a couple of things I noticed. Let me know if you want to include these in the current PR, or if I should just merge and you can put them in the next one:

- Looks like the tool tip for the ISDs is still showing the Senate District number
- The legend symbol vanishes when the ISDs radio button is selected

Looking more closely at the legend, I am wondering--right now in the legend just above the time slider controls, we have two variations on the point representations:
-Alumni & active in current year (filled and outlined)
-Active in current year only  (filled)
-->Shouldn't we also have a third case where it's alumni only? Following the logic of the above, it would be an outline with no fill? I can't remember if we discussed this and discarded it, hopefully you remember!

**Comment by eldang** [comment]
@coregis I'm jumping in now, so I'll see if I can fix the legend issue quickly.  I think the tooltip is a dependency on the updated data layer, so I'll do those two things together, after.

On the alumni & active, I think we've made this confusing by combining the legend entry with the switcher.  If we separate them, we get these options in the switcher:

- Show active only
- Show alumni & active

...and I don't think it makes sense to have a show alumni only option, because that just doesn't seem useful for RYHT's communications (though perhaps we should still check this with them).

Whereas in the legend, we need two stats:

- Active only: doesn't really need to show anything in the legend because all points are active
- Alumni & active: should show both types of circle, so people can use the legend to distinguish

Does this make sense?

**Comment by eldang** [comment]
Heh, turns out that I had misdiagnosed the issue with the school district name tooltip, so that was a much simpler fix than I'd been thinking.  Thank you for catching both of those UI things, which I just hadn't thought to tie up.

I'm going to go straight on to bringing the filtering etc back in, but I will avoid pushing any incomplete commits so if you happen to see this before I finish that work, it _is_ safe to merge this PR.

**Comment by eldang** [comment]
@coregis I think I have it all working now!  But there are a lot of moving parts, so please test thoroughly.  And I have been having ongoing issues with cached versions of files as I work on this, so it's definitely worth testing in a private browser window.

**Comment by coregis** [comment]
@eldang this is looking really great! I think we are getting close. I did notice a strange behavior when zooming to an ISD via the dropdown selector--the first screenshot below is what the **Harlingen Cons ISD** just manually zoomed, showing 2021 data; the second screenshot is the same ISD zoomed via the dropdown, showing only one program in 2021.

I believe this is being caused by naming discrepancies in the ISD spatial data and the program data we received from RYHT; for example, the RSL data uses **Harlingen CISD** for the name, which breaks the filtering. Which one do you think we should use for standardization?

image

image

**Comment by eldang** [comment]
@coregis Oh no!  I don't have an opinion on which we standardise on, but I imagine if you've found this for one district there are many others with similar issues.

Your diagnosis makes sense: the filtering will match on name alone with no fuzziness, and the stats box just counts the points that are still visible after filtering.

**Comment by eldang** [comment]
Actually one thought: how difficult would it be to mark all the datasets up with school districts identified by spatial query against the same map we're using for the boundaries?  If that's not a big lift it should solve this problem for us.

**Comment by coregis** [comment]
@eldang that is not a big lift at all! I will do it this afternoon and report back.

**Comment by coregis** [comment]
@eldang spatial joins complete, all sheets updated, and filtering/stats appears to be working! Please let me know if you notice any unexpected behavior

image

**Review by coregis — APPROVED** [review]
@eldang Everything is working and looking great. Now that the programs are filtering properly within ISDs, I'm merging into ryht-feedback-layout-changes and will finish up the landing page/map instructions styling, then (I think?!?) we should be good to share this with RYHT, but let's check in with each other first.

**Pull request merged**
