### PR TITLE
Layout changes WIP

### PR DESCRIPTION
**Pull request by eldang**

### CODE REVIEW

**Comment by coregis** [comment]
@eldang I have made most of the layout/formatting changes but keep getting really weird results when trying to float the landing page div above all others; there is some kind of interaction between the z-index and position I am using for the various divs that is not working. As you'll see I 'borrowed' your code from the WJP landing page, I figure once we get it working we can just swap out the background image for something Texasish and I will update all the CSS to match the rest of the RYHT style.

**Comment by eldang** [comment]
@coregis how odd!  I see it behaving as though you had nested the landing page inside the sidebar div, even though you clearly didn't.  I'll poke at this now and see what I can figure out, before going back to the school districts issue.

**Comment by eldang** [comment]
Aha!  The issue was the missing closing quote that I only noticed because it made the syntax highlighting weird in my text editor, and https://github.com/coregis/ryht-programs-map-2021/pull/13/commits/0d222fcc201aa2717c6ab33fe038ca7bac0a2ac9 fixes.  I'm still mystified as to why that had the specific effect that it did, but fixing it does have the landing page behaving how I think you wanted it to.

If you want the button to work how it did in the WJP project then I think the relevant CSS for that starts at https://github.com/eldang/wjp_atlas_of_legal_needs_surveys/blob/01e8905fa92d032b6e8a66e9946b01be8b3c4445/css/main.css#L311 .  But it probably makes more sense to just cut that `span` out altogether, since in fact clicking anywhere on the landing `div` has the same effect.

**Comment by coregis** [comment]
@eldang I just finished a bunch of styling and layout changes in this branch, will you please test and provide feedback when you have an opportunity? I am also going to test on my 13" laptop to see how things are looking on a much smaller screen

**Comment by coregis** [comment]
OK! Just merged, will publish main and share with our friends in Texas. Thank you!

**Pull request merged**
